# -*- coding: utf-8 -*-
"""5x5 병합표(라벨 박스) 폼 템플릿 — 레퍼런스 word_ref.hwpx 에서 추출·파라미터화.

`<보기>`/`<조건>` 라벨 박스를 레퍼런스와 픽셀 동일한 5x5 병합표로 렌더하기 위한
표 XML 템플릿(`BOGI_TABLE_TEMPLATE`)과 테두리 정의(`BORDERFILL_DEFS`).

플레이스홀더:
  {{TBL_ID}}           표 id (호출측이 고유값 주입)
  {{BF4}},{{BF8}}..{{BF15}}  borderFill id (헤더에 새로 append 한 실제 id)
  {{LABEL_SUBLIST}}    라벨 셀(<보기>) subList
  {{CONTENT_SUBLIST}}  내용 셀(ㄱ. …) subList
  {{TINY_CP}}          빈 셀(스페이서/테두리) 1pt charPr id — 행높이 11pt 강제 해제용
                       (헤더에 1pt charPr 1회 주입 후 치환)

런타임에 D:\tmp 의존 금지 — 모두 하드코딩(배포 대비).
"""
from __future__ import annotations

# 표 본문 템플릿(외곽 BF4, 셀 BF8~BF15). 빈 셀은 paraPrIDRef/charPrIDRef="0"(기본 ID).
BOGI_TABLE_TEMPLATE = (
    '<hp:tbl id="{{TBL_ID}}" zOrder="49" numberingType="TABLE" textWrap="TOP_AND_BOTTOM" textFlow="BOTH_SIDES" lock="0" dropcapstyle="None" pageBreak="CELL" repeatHeader="1" rowCnt="5" colCnt="5" cellSpacing="0" borderFillIDRef="{{BF4}}" noAdjust="0"><hp:sz width="29307" widthRelTo="ABSOLUTE" height="16073" heightRelTo="ABSOLUTE" protect="0"/><hp:pos treatAsChar="1" affectLSpacing="0" flowWithText="1" allowOverlap="0" holdAnchorAndSO="0" vertRelTo="PARA" horzRelTo="PARA" vertAlign="TOP" horzAlign="LEFT" vertOffset="0" horzOffset="0"/><hp:outMargin left="283" right="283" top="283" bottom="283"/><hp:inMargin left="0" right="0" top="141" bottom="141"/><hp:tr><hp:tc name="" header="0" hasMargin="0" protect="0" editable="0" dirty="0" borderFillIDRef="{{BF8}}"><hp:subList id="" textDirection="HORIZONTAL" lineWrap="BREAK" vertAlign="CENTER" linkListIDRef="0" linkListNextIDRef="0" textWidth="0" textHeight="0" hasTextRef="0" hasNumRef="0"><hp:p id="0" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="{{TINY_CP}}"/><hp:linesegarray><hp:lineseg textpos="0" vertpos="0" vertsize="100" textheight="100" baseline="85" spacing="600" horzpos="0" horzsize="100" flags="393216"/></hp:linesegarray></hp:p></hp:subList><hp:cellAddr colAddr="0" rowAddr="0"/><hp:cellSpan colSpan="2" rowSpan="1"/><hp:cellSz width="12599" height="691"/><hp:cellMargin left="510" right="510" top="141" bottom="141"/></hp:tc><hp:tc name="" header="0" hasMargin="1" protect="0" editable="0" dirty="0" borderFillIDRef="{{BF9}}">{{LABEL_SUBLIST}}<hp:cellAddr colAddr="2" rowAddr="0"/><hp:cellSpan colSpan="1" rowSpan="2"/><hp:cellSz width="4109" height="1182"/><hp:cellMargin left="0" right="0" top="141" bottom="141"/></hp:tc><hp:tc name="" header="0" hasMargin="0" protect="0" editable="0" dirty="0" borderFillIDRef="{{BF8}}"><hp:subList id="" textDirection="HORIZONTAL" lineWrap="BREAK" vertAlign="CENTER" linkListIDRef="0" linkListNextIDRef="0" textWidth="0" textHeight="0" hasTextRef="0" hasNumRef="0"><hp:p id="0" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="{{TINY_CP}}"/><hp:linesegarray><hp:lineseg textpos="0" vertpos="0" vertsize="100" textheight="100" baseline="85" spacing="600" horzpos="0" horzsize="100" flags="393216"/></hp:linesegarray></hp:p></hp:subList><hp:cellAddr colAddr="3" rowAddr="0"/><hp:cellSpan colSpan="2" rowSpan="1"/><hp:cellSz width="12599" height="691"/><hp:cellMargin left="510" right="510" top="141" bottom="141"/></hp:tc></hp:tr>'
    '<hp:tr><hp:tc name="" header="0" hasMargin="0" protect="0" editable="0" dirty="0" borderFillIDRef="{{BF10}}"><hp:subList id="" textDirection="HORIZONTAL" lineWrap="BREAK" vertAlign="CENTER" linkListIDRef="0" linkListNextIDRef="0" textWidth="0" textHeight="0" hasTextRef="0" hasNumRef="0"><hp:p id="0" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="{{TINY_CP}}"/><hp:linesegarray><hp:lineseg textpos="0" vertpos="0" vertsize="100" textheight="100" baseline="85" spacing="600" horzpos="0" horzsize="100" flags="393216"/></hp:linesegarray></hp:p></hp:subList><hp:cellAddr colAddr="0" rowAddr="1"/><hp:cellSpan colSpan="2" rowSpan="1"/><hp:cellSz width="12599" height="691"/><hp:cellMargin left="510" right="510" top="141" bottom="141"/></hp:tc><hp:tc name="" header="0" hasMargin="0" protect="0" editable="0" dirty="0" borderFillIDRef="{{BF11}}"><hp:subList id="" textDirection="HORIZONTAL" lineWrap="BREAK" vertAlign="CENTER" linkListIDRef="0" linkListNextIDRef="0" textWidth="0" textHeight="0" hasTextRef="0" hasNumRef="0"><hp:p id="0" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="{{TINY_CP}}"/><hp:linesegarray><hp:lineseg textpos="0" vertpos="0" vertsize="100" textheight="100" baseline="85" spacing="600" horzpos="0" horzsize="100" flags="393216"/></hp:linesegarray></hp:p></hp:subList><hp:cellAddr colAddr="3" rowAddr="1"/><hp:cellSpan colSpan="2" rowSpan="1"/><hp:cellSz width="12599" height="691"/><hp:cellMargin left="510" right="510" top="141" bottom="141"/></hp:tc></hp:tr>'
    '<hp:tr><hp:tc name="" header="0" hasMargin="0" protect="0" editable="0" dirty="0" borderFillIDRef="{{BF12}}"><hp:subList id="" textDirection="HORIZONTAL" lineWrap="BREAK" vertAlign="CENTER" linkListIDRef="0" linkListNextIDRef="0" textWidth="0" textHeight="0" hasTextRef="0" hasNumRef="0"><hp:p id="0" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="{{TINY_CP}}"/><hp:linesegarray><hp:lineseg textpos="0" vertpos="0" vertsize="100" textheight="100" baseline="85" spacing="600" horzpos="0" horzsize="100" flags="393216"/></hp:linesegarray></hp:p></hp:subList><hp:cellAddr colAddr="0" rowAddr="2"/><hp:cellSpan colSpan="5" rowSpan="1"/><hp:cellSz width="29307" height="382"/><hp:cellMargin left="510" right="510" top="141" bottom="141"/></hp:tc></hp:tr>'
    '<hp:tr><hp:tc name="" header="0" hasMargin="0" protect="0" editable="0" dirty="0" borderFillIDRef="{{BF13}}"><hp:subList id="" textDirection="HORIZONTAL" lineWrap="BREAK" vertAlign="CENTER" linkListIDRef="0" linkListNextIDRef="0" textWidth="0" textHeight="0" hasTextRef="0" hasNumRef="0"><hp:p id="0" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="{{TINY_CP}}"/><hp:linesegarray><hp:lineseg textpos="0" vertpos="0" vertsize="100" textheight="100" baseline="85" spacing="600" horzpos="0" horzsize="100" flags="393216"/></hp:linesegarray></hp:p></hp:subList><hp:cellAddr colAddr="0" rowAddr="3"/><hp:cellSpan colSpan="1" rowSpan="1"/><hp:cellSz width="849" height="924"/><hp:cellMargin left="510" right="510" top="141" bottom="141"/></hp:tc><hp:tc name="" header="0" hasMargin="0" protect="0" editable="0" dirty="0" borderFillIDRef="{{BF9}}">{{CONTENT_SUBLIST}}<hp:cellAddr colAddr="1" rowAddr="3"/><hp:cellSpan colSpan="3" rowSpan="1"/><hp:cellSz width="27609" height="1182"/><hp:cellMargin left="510" right="510" top="141" bottom="141"/></hp:tc><hp:tc name="" header="0" hasMargin="0" protect="0" editable="0" dirty="0" borderFillIDRef="{{BF14}}"><hp:subList id="" textDirection="HORIZONTAL" lineWrap="BREAK" vertAlign="CENTER" linkListIDRef="0" linkListNextIDRef="0" textWidth="0" textHeight="0" hasTextRef="0" hasNumRef="0"><hp:p id="0" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="{{TINY_CP}}"/><hp:linesegarray><hp:lineseg textpos="0" vertpos="0" vertsize="100" textheight="100" baseline="85" spacing="600" horzpos="0" horzsize="100" flags="393216"/></hp:linesegarray></hp:p></hp:subList><hp:cellAddr colAddr="4" rowAddr="3"/><hp:cellSpan colSpan="1" rowSpan="1"/><hp:cellSz width="849" height="924"/><hp:cellMargin left="510" right="510" top="141" bottom="141"/></hp:tc></hp:tr>'
    '<hp:tr><hp:tc name="" header="0" hasMargin="0" protect="0" editable="0" dirty="0" borderFillIDRef="{{BF15}}"><hp:subList id="" textDirection="HORIZONTAL" lineWrap="BREAK" vertAlign="CENTER" linkListIDRef="0" linkListNextIDRef="0" textWidth="0" textHeight="0" hasTextRef="0" hasNumRef="0"><hp:p id="0" paraPrIDRef="0" styleIDRef="0" pageBreak="0" columnBreak="0" merged="0"><hp:run charPrIDRef="{{TINY_CP}}"/><hp:linesegarray><hp:lineseg textpos="0" vertpos="0" vertsize="100" textheight="100" baseline="85" spacing="600" horzpos="0" horzsize="100" flags="393216"/></hp:linesegarray></hp:p></hp:subList><hp:cellAddr colAddr="0" rowAddr="4"/><hp:cellSpan colSpan="5" rowSpan="1"/><hp:cellSz width="29307" height="382"/><hp:cellMargin left="510" right="510" top="141" bottom="141"/></hp:tc></hp:tr>'
    '</hp:tbl>'
)

# borderFill 정의(레퍼런스 그대로, id 만 {{BFx}} 플레이스홀더). 헤더에 append 시
# 실제 id 로 치환해 itemCnt 갱신.
BORDERFILL_DEFS = {
    4: '<hh:borderFill id="{{BF4}}" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:slash type="NONE" Crooked="0" isCounter="0"/><hh:backSlash type="NONE" Crooked="0" isCounter="0"/><hh:leftBorder type="SOLID" width="0.12 mm" color="#000000"/><hh:rightBorder type="SOLID" width="0.12 mm" color="#000000"/><hh:topBorder type="SOLID" width="0.12 mm" color="#000000"/><hh:bottomBorder type="SOLID" width="0.12 mm" color="#000000"/><hh:diagonal type="SOLID" width="0.1 mm" color="#000000"/></hh:borderFill>',
    8: '<hh:borderFill id="{{BF8}}" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:slash type="NONE" Crooked="0" isCounter="0"/><hh:backSlash type="NONE" Crooked="0" isCounter="0"/><hh:leftBorder type="NONE" width="0.3 mm" color="#000000"/><hh:rightBorder type="NONE" width="0.3 mm" color="#000000"/><hh:topBorder type="NONE" width="0.3 mm" color="#000000"/><hh:bottomBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:diagonal type="SOLID" width="0.1 mm" color="#000000"/></hh:borderFill>',
    9: '<hh:borderFill id="{{BF9}}" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:slash type="NONE" Crooked="0" isCounter="0"/><hh:backSlash type="NONE" Crooked="0" isCounter="0"/><hh:leftBorder type="NONE" width="0.3 mm" color="#000000"/><hh:rightBorder type="NONE" width="0.3 mm" color="#000000"/><hh:topBorder type="NONE" width="0.3 mm" color="#000000"/><hh:bottomBorder type="NONE" width="0.3 mm" color="#000000"/><hh:diagonal type="SOLID" width="0.1 mm" color="#000000"/></hh:borderFill>',
    10: '<hh:borderFill id="{{BF10}}" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:slash type="NONE" Crooked="0" isCounter="0"/><hh:backSlash type="NONE" Crooked="0" isCounter="0"/><hh:leftBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:rightBorder type="NONE" width="0.3 mm" color="#000000"/><hh:topBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:bottomBorder type="NONE" width="0.3 mm" color="#000000"/><hh:diagonal type="SOLID" width="0.1 mm" color="#000000"/></hh:borderFill>',
    11: '<hh:borderFill id="{{BF11}}" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:slash type="NONE" Crooked="0" isCounter="0"/><hh:backSlash type="NONE" Crooked="0" isCounter="0"/><hh:leftBorder type="NONE" width="0.3 mm" color="#000000"/><hh:rightBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:topBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:bottomBorder type="NONE" width="0.3 mm" color="#000000"/><hh:diagonal type="SOLID" width="0.1 mm" color="#000000"/></hh:borderFill>',
    12: '<hh:borderFill id="{{BF12}}" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:slash type="NONE" Crooked="0" isCounter="0"/><hh:backSlash type="NONE" Crooked="0" isCounter="0"/><hh:leftBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:rightBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:topBorder type="NONE" width="0.3 mm" color="#000000"/><hh:bottomBorder type="NONE" width="0.3 mm" color="#000000"/><hh:diagonal type="SOLID" width="0.1 mm" color="#000000"/></hh:borderFill>',
    13: '<hh:borderFill id="{{BF13}}" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:slash type="NONE" Crooked="0" isCounter="0"/><hh:backSlash type="NONE" Crooked="0" isCounter="0"/><hh:leftBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:rightBorder type="NONE" width="0.3 mm" color="#000000"/><hh:topBorder type="NONE" width="0.3 mm" color="#000000"/><hh:bottomBorder type="NONE" width="0.3 mm" color="#000000"/><hh:diagonal type="SOLID" width="0.1 mm" color="#000000"/></hh:borderFill>',
    14: '<hh:borderFill id="{{BF14}}" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:slash type="NONE" Crooked="0" isCounter="0"/><hh:backSlash type="NONE" Crooked="0" isCounter="0"/><hh:leftBorder type="NONE" width="0.3 mm" color="#000000"/><hh:rightBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:topBorder type="NONE" width="0.3 mm" color="#000000"/><hh:bottomBorder type="NONE" width="0.3 mm" color="#000000"/><hh:diagonal type="SOLID" width="0.1 mm" color="#000000"/></hh:borderFill>',
    15: '<hh:borderFill id="{{BF15}}" threeD="0" shadow="0" centerLine="NONE" breakCellSeparateLine="0"><hh:slash type="NONE" Crooked="0" isCounter="0"/><hh:backSlash type="NONE" Crooked="0" isCounter="0"/><hh:leftBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:rightBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:topBorder type="NONE" width="0.3 mm" color="#000000"/><hh:bottomBorder type="SOLID" width="0.3 mm" color="#000000"/><hh:diagonal type="SOLID" width="0.1 mm" color="#000000"/></hh:borderFill>',
}

BORDERFILL_KEYS = [4, 8, 9, 10, 11, 12, 13, 14, 15]

